Repository pagopa/pagopa-checkout-auth-service, pull requests merged in 2025-03, with the labels that each got.

#27 [CHK-3762] feat(logout): logout session API implementation
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginController.kt
  src/main/kotlin/it/pagopa/checkout/authservice/services/AuthenticationService.kt
  src/test/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginControllerTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/services/AuthenticationServiceTest.kt
Labels: size/small, patch, chart-patch

#28 [CHK-3762] chore(logout): add logout session tests
  api-tests/v1/checkout-auth.api.tests.dev.json
  api-tests/v1/checkout-auth.api.tests.local.json
  api-tests/v1/checkout-auth.api.tests.uat.json
  api-tests/v1/checkout-auth.e2e.tests.local.json
Labels: size/large, patch, chart-patch

#29 Chore dev mock oi config
  helm/values-dev.yaml
Labels: size/small, skip-release, ignore-for-release

#32 [CHK-3811] Add usage of new Test collection in deploy pipeline - Dev Only
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
Labels: minor, chart-minor, size/small

#35 fix(deploy-pipeline): add missing endpoint
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#34 [CHK-3831] Add api test uat green
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#36 fix: uat tests condition
  .devops/deploy-pipelines.yml
Labels: size/small, skip-release

#39 [CHK-3845] fix(fiscalCode): handle EU fiscal code format
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/auth/UserFiscalCode.kt
  src/main/kotlin/it/pagopa/checkout/authservice/services/AuthenticationService.kt
  src/test/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/auth/DomainObjectsTest.kt
Labels: size/small, patch, chart-patch

#37 [CHK-3837] Added UAT tests blue instance
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/deploy-pipelines.yml
  helm/values-uat.yaml
Labels: minor, chart-minor, size/small

#40 chore: OI configuration for PROD env
  helm/values-prod.yaml
Labels: chart-minor, size/small, ignore-for-release

#38 feat: [CHK-3815] set initial delay for liveness and probeness. set graceful shutdown params
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: minor, chart-minor, size/small

#41 chore: set up OI parameters
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, chart-patch, ignore-for-release

#42 fix: [CHK-3883] delete all keys from Redis command
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/RedisTemplateWrapper.kt
  src/main/kotlin/it/pagopa/checkout/authservice/services/AuthenticationService.kt
  src/main/kotlin/it/pagopa/checkout/authservice/utils/JwtUtils.kt
  src/test/kotlin/it/pagopa/checkout/authservice/repositories/redis/RedisTemplateWrapperTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/services/AuthenticationServiceTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/utils/JwtUtilsTest.kt
Labels: size/small, patch, chart-patch

#43 fix: [CHK-3837] - differentiate blue and green keyspace
  .devops/code-review-pipelines.yml
  README.md
  api-tests/v1/checkout-auth.api.tests.dev.json
  api-tests/v1/checkout-auth.api.tests.uat.json
  api-tests/v1/checkout-auth.e2e.tests.local.json
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/checkout/authservice/configs/RedisConfig.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/AuthenticatedUserSessionRepository.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/OIDCAuthStateDataRepository.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/OidcKeysRepository.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/checkout/authservice/repositories/redis/WrappedRedisTemplateRepositoriesTests.kt
Labels: size/large, patch, chart-patch

#33 [CHK-3817] feat: add x-rpt-id header to all api
  api-spec/v1/openapi.yaml
  src/main/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginController.kt
  src/main/kotlin/it/pagopa/checkout/authservice/mdcutilities/MDCFilter.kt
  src/main/kotlin/it/pagopa/checkout/authservice/mdcutilities/RequestTracingUtils.kt
  src/test/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginControllerTest.kt
Labels: size/small, patch, chart-patch
