Repository pagopa/pagopa-checkout-auth-service, pull requests merged in 2025-02, with the labels that each got.

#4 [CHK-3683] feat: add github actions
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
Labels: minor, chart-minor

#8 fix: [CHK-3682] gradle fixes
  build.gradle.kts
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#9 fix: [CHK-3682] fixing repository url for uat and prod environment
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#10 feat: [CHK-3682] adding prod deploy pipeline and updating workload identity for prod
  .devops/deploy-pipelines.yml
  helm/values-prod.yaml
  src/main/resources/banner.txt
Labels: minor, chart-minor

#6 feat(oi-openapi): [CHK-3687] add OneIdentity integration
  api-spec/oneidentity/openapi.yaml
  build.gradle.kts
Labels: enhancement, minor, chart-minor, size/small

#11 fix: CHK-3682 update deprecated kotlin gradle configurations
  build.gradle.kts
Labels: size/small, patch, chart-patch

#12 feat(login-api): [CHK-3720] add api redirect logic
  .env.example
  README.md
  api-spec/v1/openapi.yaml
  build.gradle.kts
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/checkout/authservice/clients/oneidentity/OneIdentityClient.kt
  src/main/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginController.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exception/ApiError.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exception/OneIdentityConfigurationException.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exception/RestApiException.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/checkout/authservice/mdcutilities/MDCContextLifter.kt
  src/main/kotlin/it/pagopa/checkout/authservice/mdcutilities/MDCContextLifterConfiguration.kt
  src/main/kotlin/it/pagopa/checkout/authservice/mdcutilities/MDCFilter.kt
  src/main/kotlin/it/pagopa/checkout/authservice/mdcutilities/RequestTracingUtils.kt
  src/main/kotlin/it/pagopa/checkout/authservice/services/AuthLoginService.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/checkout/authservice/AuthServiceTestUtils.kt
  src/test/kotlin/it/pagopa/checkout/authservice/PagopaCheckoutAuthserviceApplicationTests.kt
  src/test/kotlin/it/pagopa/checkout/authservice/clients/oneidentity/OneIdentityClientTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginControllerTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/services/AuthLoginServiceTest.kt
  src/test/resources/application.test.properties
Labels: enhancement, minor, chart-minor, size/large

#16 fix(oi-config): update ONEIDENTITY_BASE_URL for uat
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#20 feat(cr-pipeline): [CHK-3754] update CR integration tests
  .devops/code-review-pipelines.yml
  api-tests/env/checkout-auth_dev.env.json
  api-tests/env/checkout-auth_local.env.json
  api-tests/env/checkout-auth_uat.env.json
  api-tests/v1/checkout-auth.api.tests.dev.json
  api-tests/v1/checkout-auth.api.tests.local.json
  api-tests/v1/checkout-auth.api.tests.uat.json
Labels: minor, chart-minor

#15 feat: update POST auth/token api spec
  .env.example
  .env.local.example
  README.md
  api-spec/oneidentity/openapi.yaml
  api-spec/v1/openapi.yaml
  build.gradle.kts
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/checkout/authservice/clients/oneidentity/LoginData.kt
  src/main/kotlin/it/pagopa/checkout/authservice/clients/oneidentity/OneIdentityClient.kt
  src/main/kotlin/it/pagopa/checkout/authservice/configs/RedisConfig.kt
  src/main/kotlin/it/pagopa/checkout/authservice/configs/WebClientsConfig.kt
  src/main/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginController.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exception/AuthFailedException.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exception/OneIdentityServerException.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exception/RestApiException.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/AuthenticatedUserSessionRepository.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/OIDCAuthStateDataRepository.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/OidcKeysRepository.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/RedisTemplateWrapper.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/auth/SessionToken.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/auth/UserFiscalCode.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/oidc/OidcKey.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/oidc/OidcNonce.kt
  src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/oidc/OidcState.kt
  src/main/kotlin/it/pagopa/checkout/authservice/services/AuthLoginService.kt
  src/main/kotlin/it/pagopa/checkout/authservice/services/AuthenticationService.kt
  src/main/kotlin/it/pagopa/checkout/authservice/utils/JwtUtils.kt
  src/main/kotlin/it/pagopa/checkout/authservice/utils/SessionTokenUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/checkout/authservice/clients/oneidentity/OneIdentityClientTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginControllerTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/exceptionhandler/ExceptionHandlerTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/repositories/redis/RedisTemplateWrapperTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/repositories/redis/WrappedRedisTemplateRepositoriesTests.kt
  src/test/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/auth/DomainObjectsTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/services/AuthLoginServiceTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/services/AuthenticationServiceTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/utils/JwtUtilsTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/utils/SessionTokenUtilsTest.kt
  src/test/resources/application.test.properties
Labels: minor, chart-minor, size/large

#18 Chk 3707 get user info api
  .devops/code-review-pipelines.yml
  api-tests/env/checkout-auth_dev.env.json
  api-tests/env/checkout-auth_local.env.json
  api-tests/env/checkout-auth_uat.env.json
  api-tests/v1/checkout-auth.api.tests.dev.json
  api-tests/v1/checkout-auth.api.tests.local.json
  api-tests/v1/checkout-auth.api.tests.uat.json
  src/main/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginController.kt
  src/main/kotlin/it/pagopa/checkout/authservice/exception/SessionValidationException.kt
  src/main/kotlin/it/pagopa/checkout/authservice/services/AuthenticationService.kt
  src/main/kotlin/it/pagopa/checkout/authservice/utils/SessionTokenUtils.kt
  src/test/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginControllerTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/services/AuthenticationServiceTest.kt
  src/test/kotlin/it/pagopa/checkout/authservice/utils/SessionTokenUtilsTest.kt
Labels: minor, chart-minor, size/large
